version: "3.8"

services:
  postgres_dino:
    image: postgres:15.4-alpine3.18
    container_name: postgres_dino
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  # redis_dino:
  #   image: redis:7.2-alpine
  #   container_name: redis_dino
  #   ports:
  #     - 6379:6379

volumes:
  data: